# Generated by Django 5.0.6 on 2024-06-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediadev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('livre', 'Livre'), ('dvd', 'Dvd'), ('cd', 'Cd')], max_length=150)),
                ('media_id', models.PositiveIntegerField()),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediadev.membre')),
            ],
        ),
    ]
